### ISSUE TITLE
Deploying /website/* on live site could cause problems?

### ISSUE THREAD

**Issue by mccalluc** [Caleydo/website#73]
(Apologies in advance if I'm confused here.)

I just found the earlier conversation on [slack](https://caleydo.slack.com/archives/website/p1463677843000064) about `master` vs `gh-pages`. So the fact that I needed `/website` on #72 was only because I was on `gh-pages`, and the branch has been [configured](https://github.com/Caleydo/website/commit/57c1e3ed0e720a05930652afc3323dd2ff76fe72) to serve from that path. I'm less sure now that that was a good change; depends on the workflow we want to encourage?

This might be either a feature or a bug, but the live site is serving both [master](http://www.caleydo.org/documentation/) and [gh-pages](http://www.caleydo.org/website/documentation/). (Note the differences in the sidebar.) I guess Jenkins builds and deploys from every branch? I don't understand how that part works.

Having `/website` (ie `gh-pages`) deployed worries me a little: Google finds pages even if you don't go out of your way to advertise them, which is probably not what we want here? And then when `gh-pages` is merged to `master` there will be dead links in search results.

Proposals:
- Configure Jenkins so that only the `master` branch is deployed
- Clarify the future of `gh-pages`: If we plan to work on documentation for a while before merging, it might be good to good to move it to a branch whose name reflects that?

**Comment by alexsb** [comment]
It's a feature. We want to host the documentation on a public website, because we point students to it, but it's not ready to be on the main page.

Is there a specific problem with using the gh-pages branch?

**Comment by mccalluc** [comment]
No, just my confusion: I just hadn't realized that both branches were being deployed, and that that was by design. Closing. Thanks!
